language: python
python:
    - "2.7"

install:
  - pip install -r external_requirements.txt  --index-url https://pypi.python.org/simple
  - pip install -r internal_requirements.txt  --index-url https://testpypi.python.org/pypi

script:
    - pushd package
    - python setup.py develop
    - popd
    - python runtests.py --with-coverage  --cover-package=package --exclude setup.py

after_success:
    - coveralls
    
#notifications:
# webhools: https://qualisystems.getbadges.io/api/app/webhook/{will be added later}
