language: python
python:
    - "2.7"

install:
  - bash ./install_dependencies.sh

script:
    - pushd package
    - pip install "cloudshell-automation-api>=7.1.0.0,<7.2.0.0"  --index-url https://testpypi.python.org/simple
    - python setup.py develop
    - popd
    - python runtests.py --with-coverage  --cover-package=package --exclude setup.py

after_success:
    - coveralls
    
#notifications:
# webhools: https://qualisystems.getbadges.io/api/app/webhook/{will be added later}
